### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by CNYuYang** [Abingcbc/MIT6.824#1]
同学，你是否遇到到数第二个测试无法通过，一直卡死的情况？
reduce parallelism test

**Comment by Abingcbc** [comment]
时间有点久，我有点忘了是不是倒数第二个测试了。。。我lab1遇到卡死的情况是，有些worker会crash掉，或者其他原因不返回task的结果。所以master要为每个task设置一个超时，如果超时，要重新分配给其他worker。
你可以看一下lab的测试代码，应该就能知道它为什么卡死了。
